my_blog/article/urls.py
from django.urls import path
from . import views

# 用于在 html 文件中，编写超链接，以及从 views.py 反向url找到对应的视图函数
# {% url 'article:article_list'%}
app_name = 'article'

urlpatterns = [
	path('article-list/', views.article_list, name='article_list'),
	path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
	path('article-create/', views.article_create, name='article_create'),
	path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
	path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
	path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('password-reset/', include('password_reset.urls')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('article/', include('article.urls', namespace='article')),
    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('register/', views.user_register, name='register'),
	path('edit/<int:id>/', views.profile_edit, name='edit'),
]

my_blog/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
# 引入内置信号
# from django.db.models.signals import post_save
# 引入信号接收器的装饰器
# from django.dispatch import receiver


# 用户扩展信息
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
	phone = models.CharField(max_length=20, blank=True)
	avatar = models.ImageField(upload_to='avatar/%Y/%m%d/', blank=True)
	bio = models.TextField(max_length=500, blank=True)

	def __str__(self):
		return 'user {}'.format(self.user.username)


# 信号接受函数, 每当新建 User 实例时自动调用
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
# 	if created:
# 		Profile.objects.create(user=instance)


# # 信号接收函数，每当更新 User 实例时自动调用
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
# 	instance.profile.save()

my_blog/userprofile/forms.py
# 从 django 引入表单类, 和模型类似
from django import forms

# 从 django 自带的用户app 的模型中导入用户的模型
# 表单类和模型一一对应的存在
from django.contrib.auth.models import User
# 引入 Profile 模型
from .models import Profile


# 不修改数据库的字段 只用继承 forms.Form 
class UserLoginForm(forms.Form):
	"""登录表单类，继承了 forms.Form 类"""
	username = forms.CharField()
	password = forms.CharField()

class UserRegisterForm(forms.ModelForm):
	"""用户注册表单类"""
	password = forms.CharField()
	password2 = forms.CharField()

	# 定义表所对应的模型，以及需要修改的字段
	class Meta:
		model = User
		fields = ('username', 'email')

	def clean_password2(self):
		data = self.cleaned_data
		if data.get('password') == data.get('password2'):
			return data.get('password')
		else:
			raise forms.ValidationError("密码输入不一致，请重试。")
		
# 需要对模型发生修改 要从 froms 继承ModelForm		
class ProfileForm(forms.ModelForm):	

	# 还要定义 对应修改的模型名称以及字段
	class Meta:
		model = Profile
		fields = ('phone', 'avatar', 'bio')
		

my_blog/userprofile/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .forms import UserLoginForm, UserRegisterForm, ProfileForm
from .models import Profile


def user_login(request):
	if request.method == "POST":
		user_login_form = UserLoginForm(data=request.POST)
		if user_login_form.is_valid():
			# .cleaned_data 清洗出合法数据,返回包含字段的字典，也就是一致的格式
			data = user_login_form.cleaned_data
			# 检验账号、密码是否正确匹配数据库中的某个用户
			user = authenticate(username=data['username'], password=data['password'])
			if user:
				# 用户数据保存在 session 中，即实现了登录动作
				login(request, user)
				return redirect("article:article_list")
			else:
				return HttpResponse("账号或密码输入错误。请重新输入~")
		else:
			return HttpResponse("账号或密码输入不合法")

	elif request.method == 'GET':
		user_login_form = UserLoginForm()
		context = {'form': user_login_form}
		return render(request, 'userprofile/login.html', context)
	else:
		return HttpResponse("请使用 GET 或 POST 请求数据")


def user_logout(request):
	"""用户退出登录"""
	logout(request)
	return redirect("article:article_list")


def user_register(request):
	"""用户注册"""
	if request.method == "POST":
		# 将请求数据传递给表单实例
		user_register_form = UserRegisterForm(data=request.POST)
		if user_register_form.is_valid():
			new_user = user_register_form.save(commit=False)
			new_user.set_password(user_register_form.cleaned_data['password'])
			new_user.save()
			login(request, new_user)
			return redirect("article:article_list")
		else:
			return HttpResponse("注册表单输入有误。请重新输入~")
	elif request.method == 'GET':
		user_register_form = UserRegisterForm()
		context = {'form': user_register_form}
		return render(request, 'userprofile/register.html', context)
	else:
		return HttpResponse("请使用GET或POST请求数据")


# 编辑用户信息
@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
	user = User.objects.get(pk=id)
	# profile = Profile.objects.get(user_id=id)

	if Profile.objects.filter(user_id=id).exists():
		profile = Profile.objects.get(user_id=id)
	else:
		profile = Profile.objects.create(user=user)

	if request.method == 'POST':
		# 验证修改数据者，是否为用户本人
		if request.user != user:
			return HttpResponse("你没有权限修改此用户信息。")

		# 从 request.FILES 中，通过参数传递给表单类
		profile_form = ProfileForm(request.POST, request.FILES)
		if profile_form.is_valid():
			# 取得清洗后的合法数据
			profile_cd = profile_form.cleaned_data
			# 更新 profile 表
			profile.phone = profile_cd.get('phone')
			profile.bio = profile_cd.get('bio')
			if 'avatar' in request.FILES:
				profile.avatar = profile_cd.get("avatar")
			profile.save()
			# 带参数的 redirect()
			return redirect("userprofile:edit", id=id)
		else:
			return HttpResponse("注册的表单输入有误。请重新输入~")
	elif request.method == 'GET':
		context = {'profile': profile, 'user': user}
		return render(request, 'userprofile/edit.html', context)
	else:
		return HttpResponse("请使用 GET 或 POST　请求数据")

my_blog/templates/userprofile/edit.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
	用户信息
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用户名: {{ user.username }}</div>
            <br>

            {% if profile.avatar %}
                <div class="col-md-4"></div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <h4 class="col-md-4">暂无头像</h4>
            {% endif %}
            <br>
            <br>

            <form method="post" enctype="multipart/form-data" action=".">
                {% csrf_token %}
                <!-- avatar -->
                <div class="form-group">
                    <label for="avatar">上传头像</label>
                    <input class="form-control-file" type="file" name="avatar" id="avatar">
                </div>

                <!-- phone -->
                <div class="form-group col-md-4">
                    <label for="phone">电话</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>

                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">简介</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>

                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

my_blog/templates/userprofile/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
	用户登录
{% endblock title %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-12">
			<br>
			<form method="post" action=".">
				{% csrf_token %}
				<div class="form-group">
					<label for="username">用户名</label>
					<input type="text" name="username" class="form-control" id="username">
				</div>

				<div class="form-group">
					<label for="password">密码</label>
					<input type="password" name="password" class="form-control" id="password">
				</div>

				<h5>新人?</h5>
				<h5>
					<a href="{% url "userprofile:register" %}">还没注册？点击加入我们~</a>
				</h5>
				<br>

				<button type="submit" class="btn btn-primary">登录</button>
				<br>
				<h5>
					<a href="{% url "password_reset_recover" %}">重置密码</a>
				</h5>

			</form>
		</div>
	</div>
</div>
	
{% endblock content %}

my_blog/templates/userprofile/register.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
	用户注册
{% endblock title %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-12">
	<form method="post" action=".">
		{% csrf_token %}
		<br>
		<div class="form-group col-md-4">
			<label for="username">昵称</label>
			<input type="text" name="username" class="form-control" id="username" required>
		</div>
		

		<div class="form-group col-md-4">
			<label>Email</label>
			<input type="text" name="email" class="form-control" id="email">
		</div>

		
		<div class="form-group col-md-4">
			<label>设置密码</label>
			<input type="password" name="password" class="form-control" id="password" required>
		</div>

		<div class="form-group col-md-4">
			<label>确认密码</label>
			<input type="password" name="password2" class="form-control" id="password2" required>	
		</div>

		<button type="submit" class="btn btn-primary">注册</button>
	</form>
			
		</div>
	</div>
</div>
{% endblock content %}