my_blog/article/urls.py
from django.urls import path
from . import views

# 用于在 html 文件中，编写超链接，以及从 views.py 反向url找到对应的视图函数
# {% url 'article:article_list'%}
app_name = 'article'

urlpatterns = [
	path('article-list/', views.article_list, name='article_list'),
	path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
	path('article-create/', views.article_create, name='article_create'),
	path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
	path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
	path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
	path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('password-reset/', include('password_reset.urls')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('article/', include('article.urls', namespace='article')),
    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('register/', views.user_register, name='register'),
	path('edit/<int:id>/', views.profile_edit, name='edit'),
]

my_blog/article/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone


class ArticlePost(models.Model):
	# 文章作者
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	# 文章标题
	title = models.CharField(max_length=100)
	# 文章正文
	body = models.TextField()
	# 文章阅读量
	total_views = models.PositiveIntegerField(default=0)
	# 文章创建时间
	created = models.DateTimeField(default=timezone.now)
	# 文章更新时间
	updated = models.DateTimeField(auto_now=True)

	# 内部类 Meta ，用于给模型定义元数据
	class Meta:
		# 指定模型返回的数据的排列顺序
		ordering = ('-created',)

	def get_absolute_url(self):
		return reverse('article:article_detail', args=[self.id])

	# 函数 __str__ 定义调用对象的 str()方法时的返回值内容
	def __str__(self):
		# 将文章的标题返回
		return self.title

my_blog/article/forms.py
# 导入表单类
from django import forms
# 导入文章模型
from .models import ArticlePost


# 文章表单类
class ArticlePostForm(forms.ModelForm):
	"""
	通过该表单类提交的数据，需要直接和数据库交互
	所以需要继承 forms.ModelsForm
	不是单纯的一个表单
	"""
	class Meta:
		# 指明数据模型来源
		model = ArticlePost
		# 定义表单包含的字段
		fields = ('title', 'body')

my_blog/article/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.db.models import Q

# 认证应用
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

import markdown

from .forms import ArticlePostForm
from .models import ArticlePost

from comment.models import ArticleComment

def article_list(request):
	"""首页展示所有文章"""
	# 根据GET请求中查询条件
	# 返回不同排序的对象列表
	search = request.GET.get('search')
	order = request.GET.get('order')
	if search:
		if order == 'total_views':
			# Q 对象 进行联合搜索
			article_list = ArticlePost.objects.filter(
				Q(title__icontains=search) |
				Q(body__icontains=search)
			).order_by('-total_views')
		else:
			article_list = ArticlePost.objects.filter(
				Q(title__icontains=search) |
				Q(body__icontains=search)
			)
	else:
		# 将 search 参数重置为空
		search = ''
		if order == 'total_views':
			article_list = ArticlePost.objects.all().order_by('-total_views')
		else:
			article_list = ArticlePost.objects.all()


	# 文章分页展示
	paginator = Paginator(article_list, 2)
	page = request.GET.get('page')
	articles = paginator.get_page(page)
	context = {'articles': articles, 'order': order, 'search': search}

	return render(request, 'article/list.html', context)


def article_detail(request, id):
	"""阅读指定文章"""
	# 取出相应文章
	article = ArticlePost.objects.get(id=id)
	# 浏览量 +1
	if request.user != article.author:
	# 保证作者每次修改和阅读，不给自己增加阅读量
		article.total_views += 1
		article.save(update_fields=['total_views'])

	# 修改 Markdown 语法渲染
	md = markdown.Markdown(
		extensions = [
				'markdown.extensions.extra',
				'markdown.extensions.codehilite',
				'markdown.extensions.toc',
			]
		)
	article.body = md.convert(article.body)

	# 获取文章的评论
	comments = ArticleComment.objects.filter(article=id)
	# 需要传递给模板的对象
	context = {'article': article, 'toc': md.toc, 'comments': comments}
	# 载入模板，并返回 context 对象
	return render(request, 'article/detail.html', context)


@login_required(login_url='/userprofile/login/')
def article_create(request):
	"""创建一篇文章"""
	# 判断用户是否提交数据
	if request.method == "POST":
		# 将提交的数据赋值到表单实例中
		article_post_form = ArticlePostForm(data=request.POST)
		# 根据请求中用户的 id 
		author_name = request.user.id
		# 判断提交的数据是否满足模型要求
		if article_post_form.is_valid():
			# 保存数据，但暂时不提交到数据库中
			new_article = article_post_form.save(commit=False)
			# 通过id获取当前登录的用户名，作为文章署名
			new_article.author = User.objects.get(id=author_name)
			# 将文章保存到数据库中
			new_article.save()
			# 完成后返回到文章列表
			return redirect("article:article_list")
		# 如果数据不合法，返回错误信息
		else:
			return HttpResponse("表单内容有无，请重新填写。")
	# 用户请求写文章
	else:
		# 创建表单实列
		article_post_form = ArticlePostForm()
		# 赋值上下文
		context = {'aritcle_post_form': article_post_form}
		# 返回模板
		return render(request, 'article/create.html', context)


@login_required(login_url='/userprofile/login/')
def article_delete(request, id):
	"""不安全的删除文章"""
	# 根据条件选择要删除的文章
	article = ArticlePost.objects.get(id=id)
	article.delete()
	return redirect("article:article_list")


@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
	"""安全删除文章"""
	if request.method == 'POST':
		article = ArticlePost.objects.get(pk=id)
		article.delete()
		return redirect("article:article_list")
	else:
		return HttpResponse("仅允许post请求")


@login_required(login_url='/userprofile/login/')
def article_update(request, id):
	"""更新文章视图"""
	article = ArticlePost.objects.get(pk=id)

	# 过滤非作者用户修改文章
	if request.user != article.author:
		return HttpResponse("抱歉，你无权修改这篇文章。")

	if request.method == "POST":
		article_post_form = ArticlePostForm(data=request.POST)
		if article_post_form.is_valid():
			article.title = request.POST.get('title')
			article.body = request.POST.get('body')
			article.save()
			return redirect('article:article_detail', id=id)
		else:
			HttpResponse("请检查输入内容是否有误！并重新填写相关内容。")
	else:
		article_post_form = ArticlePostForm()
		context = {'article': article, 'article_post_form': article_post_form}
		return render(request, 'article/update.html', context)

my_blog/templates/article/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} 写文章 {% endblock title %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<br>
				<form method="post" action=".">
					{% csrf_token %}
					<div class="form-group">
						<label for="title">文章标题</label>
						<input type="text" class="form-control" id="title" name="title">
					</div>

					<div class="form-group">
						<label for="body">文章正文</label>
						<textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
					</div>

					
					<button type="submit" class="btn btn-primary">完成</button>
					
				</form>


			</div>
		</div>
	</div>

{% endblock content %}

my_blog/templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
	文章详情
{% endblock title %}

{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <!-- 标题及作者 -->
        <div class="col-9">
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>
                    👩‍💻作者：{{ article.author }}
                    {% if user == article.author %}
                        · <a href="#" onclick="confirm_safe_delete()">☠删除本文</a>
                        · <a href="{% url "article:article_update" article.id %}">🖊编辑文章</a>
                     {% endif %} 
                </div>

                <div>
                    👁浏览: {{ article.total_views }} 
                </div>

                <form 
                    style="display:none;" 
                    id="safe_delete" 
                    action="{% url 'article:article_safe_delete' article.id %}" 
                    method="POST">
                    {% csrf_token %}
                    <button type="submit">发送</button>
                </form>
            </div>
        </div>

        <!-- 新增的目录 -->
        <div class="col-3 mt-4">
            <h4><strong>📑目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>

        <!-- 文章正文 -->
        <div class="col-9">
            <p>{{ article.body|safe }}</p>
        </div>

        <!-- 发表评论 -->
        <hr>
        {% if user.is_authenticated %}
            <div class="col-9">
                <form action="{% url 'comment:post_comment' article.id%}" 
                      method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>📢我也要发言:</strong>
                        </label>

                        <textarea 
                            type="text" 
                            class="form-control" 
                            id="body" 
                            name="body" 
                            rows="2"></textarea>

                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary">✈发送</button>
                    </div>
                </form>
            </div>
            <br>
        {% else %}
            <br>
            <div class="col-9">
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                </h5>
            </div>
            <br>
        {% endif %}

        <!-- 显示评论 -->
        <div class="col-9">
            <h4>🎉共有{{ comments.count}}条评论🎉</h4>
            {% for comment in comments %}
                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.user }}
                    </strong> 于
                    <span style="color: green">
                        {{ comment.created|date:"Y-m-d H:i:s" }}
                    </span> 时说:
                </p>
                <pre style="font-family: inherit; font-size: 1em;">{{ comment.body }}</pre>
            {% endfor %}
        </div>

    </div>
</div>

<script type="text/javascript">
    function confirm_safe_delete() {
        layer.open({
            title: "确认删除",
            content: "确认删除这篇文章吗？",
            yes: function(index, layero) {
                // body...
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }
</script>

{% endblock content %}

my_blog/templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}">
                    最新
                </a>
            </li>

            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}">
                    最热
                </a>
            </li>
        </ol>
    </nav>

    <!-- 新增, 搜索栏-->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline">
                <label class="sr-only">content</label>
                <input class="form-control mb-2 mr-sm-2" 
                       type="text" 
                       name="search" 
                       placeholder="搜索文章... " 
                       required>
                <button type="submit" class="btn btn-primary">搜索🔍</button>
            </form>
        </div>
    </div>

    <!-- 新增, 搜索提示语-->
    {% if search %}
        {% if articles %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下: </h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关文章</h4>
        {% endif %}
    {% endif %}

    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>

                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id%}" class="btn btn-primary">阅读本文 📃</a>
                </div>

                <!-- 显示浏览量 -->
                <span>
                    <small class="col align-self-end" style="color: gray;">
                        浏览: {{ article.total_views }} 👀
                    </small>
                </span>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!-- 分页 -->
<div class="pagination row">
    <div class="m-auto">
        <span class="step-links">
            {% if articles.has_previous %}
                <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                    {{ articles.previous_page_number }}
                </a>
            {% endif %} 
        </span>
        
        <span class="current btn btn-danger btn-lg">
            {{ articles.number }}
        </span>
    
        {% if articles.has_next %}
            <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                {{ articles.next_page_number }}
            </a>
            <span>...</span>
            <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}" class="btn btn-success">
                {{ articles.paginator.num_pages }} &raquo
            </a>
        {% endif %} 
        
    </div>
</div>    
{% endblock content %}

my_blog/templates/article/update.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} 更新文章 {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
            	<div class="form-group">
            		<label for="title">文章表题</label>
            		<input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
            	</div>
            	<div class="form-group">
            		<label for="body">文章正文</label>
            		<textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
            	</div>
            	<button type="submit" class="btn btn-primary">完成</button>
            </form>

        </div>
    </div>
</div>
{% endblock content %}